// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmsm8eBFQ_UL0rZW9Y03Ny2ObIzqWXaxI',
    appId: '1:878769091086:web:d5266957040e54b53fc25f',
    messagingSenderId: '878769091086',
    projectId: 'prodev-8bc3b',
    authDomain: 'prodev-8bc3b.firebaseapp.com',
    storageBucket: 'prodev-8bc3b.firebasestorage.app',
    measurementId: 'G-EPWR5XPYME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBufcB_gAjUzZSvZyvzHBbh1VfiDmcy7PI',
    appId: '1:878769091086:android:387feb8f75a8ba923fc25f',
    messagingSenderId: '878769091086',
    projectId: 'prodev-8bc3b',
    storageBucket: 'prodev-8bc3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRjBT6FCszAFwJJ3gjZnYJjYcNJhto_eA',
    appId: '1:878769091086:ios:b040c81aab1931843fc25f',
    messagingSenderId: '878769091086',
    projectId: 'prodev-8bc3b',
    storageBucket: 'prodev-8bc3b.firebasestorage.app',
    iosBundleId: 'com.example.prodev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRjBT6FCszAFwJJ3gjZnYJjYcNJhto_eA',
    appId: '1:878769091086:ios:b040c81aab1931843fc25f',
    messagingSenderId: '878769091086',
    projectId: 'prodev-8bc3b',
    storageBucket: 'prodev-8bc3b.firebasestorage.app',
    iosBundleId: 'com.example.prodev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmsm8eBFQ_UL0rZW9Y03Ny2ObIzqWXaxI',
    appId: '1:878769091086:web:df25af3d998b33d93fc25f',
    messagingSenderId: '878769091086',
    projectId: 'prodev-8bc3b',
    authDomain: 'prodev-8bc3b.firebaseapp.com',
    storageBucket: 'prodev-8bc3b.firebasestorage.app',
    measurementId: 'G-ZN4CPK54Q4',
  );
}
